# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# use 'goreleaser check' to chekc the yaml file 
# user 'goreleaser init' to generate a new yaml file


project_name: snyk-jira-sync

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
universal_binaries:
  - replace: true
    name_template: "{{.ProjectName}}-macos"
archives:
  - format: binary
    name_template: "{{.ProjectName}}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
