# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
jobs:
  build-test-monitor:
      docker:
        # specify the version
        - image: circleci/golang:1.13

      steps:
        - checkout
        - run: go test -v
        - snyk/scan:
            fail-on-issues: true
            monitor-on-build: true
            token-variable: SNYK_TOKEN

  build-test:
      docker:
        # specify the version
        - image: circleci/golang:1.13

      steps:
        - checkout
        - run: go test -v
        - snyk/scan:
            fail-on-issues: true
            monitor-on-build: false
            token-variable: SNYK_TOKEN
        - run: ./generate-binaries.sh
        - persist_to_workspace:
            root: .
            paths:
              - dist/*

  publish-github-release:
    docker:
      - image: gcr.io/snyk-technical-services/cicd-github
        auth:
          username: _json_key
          password: $GCLOUD_GCR_SNYK_TS_READER
    steps:
      - attach_workspace:
          at: ./dist
      - run:
          name: "Publish Release on GitHub"
          command: |    
            VERSIONJUMP=$(git log --oneline -1 --pretty=%B | cat | awk -F '/' '{print $1}')   
            VERSION=$(./nextver.sh "$VERSIONJUMP")
            ghr $VERSION -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ./dist/

workflows:
  version: 2.1
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-test-monitor
  build-test-monitor:
    jobs:
      - build-test-monitor:
          filters:
            branches:
              only:
                  - master
  build-test:
      jobs:
        - build-test:
            filters:
              branches:
                ignore:
                  - master

  publish-github-release:
      jobs:
        - publish-github-release:
            filters:
              branches:
                only:
                  - master
      