version: 2.1

orbs:
  gh: circleci/github-cli@2.7.0

jobs:
  build-test-monitor:
      docker:
        # specify the version
        - image: cimg/go:1.24
      steps:
        - checkout
        - run:
            name: "Test"
            command: |
              go test -v
        - run:
            name: "Generate Binaries"
            command: |
              ./generate-binaries.sh
        - persist_to_workspace:
            root: .
            paths:
              - dist/*

  build-test:
      docker:
        # specify the version
        - image: cimg/go:1.24

      steps:
        - checkout
        - run:
            name: "Test"
            command: |
              go test -v

  publish-github-release:
    docker:
      - image: cimg/base:2025.04
    steps:
      - checkout
      - gh/setup
      - attach_workspace:
          at: .
      - run:
          name: "Generate Checksums"
          command: |
            sha256sum dist/snyk-jira-sync-linux > dist/snyk-jira-sync-linux.sha256
            sha256sum dist/snyk-jira-sync-macos > dist/snyk-jira-sync-macos.sha256
            sha256sum dist/snyk-jira-sync-win.exe > dist/snyk-jira-sync-win.exe.sha256
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat VERSION)
            gh release create v${VERSION} --generate-notes --title "Release v${VERSION}" --repo ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}

workflows:
  build-test-monitor-publish:
    jobs:
      - build-test-monitor:
          filters:
            branches:
              only:
                  - master
      - publish-github-release:
          requires:
            - build-test-monitor
          filters:
            branches:
              only:
                - master
  build-test-workflow:
      jobs:
        - build-test:
            filters:
              branches:
                ignore:
                  - master